### ISSUE TITLE
test: asdaasdad

### ISSUE THREAD

**Issue by CrisVonZalez** [ViciusChile/Scraper_Dealer#1]
- asd[asdad ]

**Comment by kimuracl** [comment]
Buen mensaje... [😊]

Saludos,

Juan Pablo Reyes Sep??lveda

---

De: Cristopher Gonzalez notifications@github.com
Enviado: miércoles, 28 de septiembre de 2016 14:12
Para: ViciusChile/Scraper_Dealer
Asunto: [ViciusChile/Scraper_Dealer] asdaasdad (#1)
-   asd[asdad ]

**Comment by CrisVonZalez** [comment]
Se cierra Issue, se soluciona aplicando aasafsfsfadsdaasda asd adada  a a asd
